#pragma config(Sensor, in1,    AutoPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    LFright,             sensorLineFollower)
#pragma config(Sensor, in5,    LFrear,              sensorLineFollower)
#pragma config(Sensor, in6,    LFleft,              sensorLineFollower)
#pragma config(Sensor, in7,    armAngle,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  QEtower,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  SOLclaw,             sensorDigitalOut)
#pragma config(Sensor, dgtl4,  QEleft,              sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  QEright,             sensorQuadEncoder)
#pragma config(Sensor, dgtl10, clawLimitSensor,     sensorTouch)
#pragma config(Sensor, dgtl11, startButton,         sensorTouch)
#pragma config(Motor,  port1,           leftRear,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           arm1,          tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           arm2,          tmotorNormal, openLoop)
#pragma config(Motor,  port5,           tower1,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           tower2,        tmotorNormal, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorNormal, openLoop)
#pragma config(Motor,  port9,           rightRear,     tmotorNormal, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**  *****FILE COMMENT*****
FOR: "competitionBotRC.c"
AUTHOR: Matthew Walker 

A much simpler and earlier version of ExamR,
with less code specific to gateway.

Controls:
  setMotorsToRC() controls, plus:
  7U - straight line forward
  7R - 90deg right turn
  7L - 90deg left turn  
*/



#ifndef MAIN_USED
  #define CBRC_IS_MAIN
  #define MAIN_USED
#endif

//#define USE_SONAR_STOP_AND_DETAIL_MODE

#include "controlCode.c"
#include "QEturning.c"
#include "QEstraightLine.c"

#ifdef CBRC_IS_MAIN
task main(){
#else
void competitionBotRCmain(){
#endif
  static int B7UReleased = true;
  while(true){
    setMotorsToRC();
    if(vexRT[Btn7U]){
      B7UReleased = true;
      QePidLoopContents(1000,false);//ridulously high number
    }else if (B7UReleased) {
      B7UReleased = false;
      resetWheelQEs();
    }
    if(vexRT[Btn7R]){
      turn90(RIGHT,true);
    }
    if(vexRT[Btn7L]){
      turn90(LEFT,true);
    }
  }
}
