#pragma config(Sensor, in1,    AutoPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    LFright,             sensorLineFollower)
#pragma config(Sensor, in5,    LFrear,              sensorLineFollower)
#pragma config(Sensor, in6,    LFleft,              sensorLineFollower)
#pragma config(Sensor, in7,    armAngle,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  QEtower,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  SOLclaw,             sensorDigitalOut)
#pragma config(Sensor, dgtl4,  QEleft,              sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  QEright,             sensorQuadEncoder)
#pragma config(Sensor, dgtl10, clawLimitSensor,     sensorTouch)
#pragma config(Sensor, dgtl11, startButton,         sensorTouch)
#pragma config(Motor,  port1,           leftRear,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           arm1,          tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           arm2,          tmotorNormal, openLoop)
#pragma config(Motor,  port5,           tower1,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           tower2,        tmotorNormal, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorNormal, openLoop)
#pragma config(Motor,  port9,           rightRear,     tmotorNormal, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**  *****FILE COMMENT*****
FOR: "LFturning.c"
AUTHOR: Matthew Walker 

  A utility for turning untill a line is under the sensors.
  works?
  
*/

#ifndef MAIN_USED
  #define LFT_IS_MAIN
  #define MAIN_USED
#endif

#include "controlCode.c"
#include "QEturning.c"


/**
  turns until finds a line
  blocks until finished
*/
void turnUntilLine(int approxLenght, bool dir, bool stopThere){
  resetWheelQEs();
  setTurnDir(dir);
  //if on the line, waits until off
  while (getLFl()<WHITE_FLOOR || getLFr()<WHITE_FLOOR){
    QeSpinPidLoopContents();
    //QeTurnPidLoopContents(approxLenght);
  }
  //then starts checking
  while (getLFl()>WHITE_FLOOR && getLFr()>WHITE_FLOOR){
    QeSpinPidLoopContents();
    //QeTurnPidLoopContents(approxLenght);
  }
  if (stopThere){
    stopBothWheels();
    wait1Msec(WAIT_AFTER_STOP_TIME);
    releaseBothWheels();
  }
}

void turnUntilLineDeg(int approxDeg, bool dir, bool stopThere){
  turnUntilLine(approxDeg*ONE_DEG,dir,stopThere);
}
/**
assumes 90 degree turn
*/
void turnUntilLine(bool dir, bool stopThere){
  turnUntilLine(90*ONE_DEG,dir,stopThere);
}

#ifdef LFT_IS_MAIN
task main(){
#else
void LFturningMain(){
#endif
  while(vexRT[Btn6D] != 1){//press Btn6D to get out
    setMotorsToRC();
    if (vexRT[Btn8R]){
      turnUntilLine(RIGHT,true);
    }else if (vexRT[Btn8L]){
      turnUntilLine(LEFT,true);
    }
  }
}
