#pragma config(Sensor, in1,    pgrmSelect1,         sensorPotentiometer)
#pragma config(Sensor, in3,    LFfront,             sensorLineFollower)
#pragma config(Sensor, in4,    LFright,             sensorLineFollower)
#pragma config(Sensor, in5,    LFcentre,            sensorLineFollower)
#pragma config(Sensor, in6,    LFleft,              sensorLineFollower)
#pragma config(Sensor, dgtl1,  QCright,             sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  QCleft,              sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  FSONAR,              sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  PNEUMATIC,           sensorDigitalOut)
#pragma config(Motor,  port1,           leftRear,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           rightFront,    tmotorNormal, openLoop)
#pragma config(Motor,  port9,           rightRear,     tmotorNormal, openLoop)
#pragma config(Motor,  port10,          leftFront,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  while(true)
  {
    if(vexRT[Btn7U] == 1){
      SensorValue[PNEUMATIC] = 1;
    }else{
      SensorValue[PNEUMATIC] = 0;
    }
  }
}
